services:
  base:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: vpn-base:latest

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  migrations:
    build:
      context: .
      dockerfile: ./alembic/Dockerfile
    depends_on:
      db:
        condition: service_healthy
      base:
        condition: service_started
    env_file:
      - .env
    volumes:
      - core_code:/app/core

  admin:
    build:
      context: .
      dockerfile: ./admin/Dockerfile
    depends_on: [db, base]
    env_file:
      - .env
    restart: on-failure
    volumes:
      - core_code:/app/core

  bot:
    build:
      context: .
      dockerfile: ./bot/Dockerfile
    depends_on: [db, base]
    env_file:
      - .env
    restart: on-failure
    volumes:
      - core_code:/app/core
    
  billing_daemon:
    build:
      context: .
      dockerfile: ./scripts/Dockerfile
    depends_on: [db, base]
    env_file:
      - .env
    restart: on-failure
    volumes:
      - core_code:/app/core

  nginx:
    build: ./nginx
    depends_on: [admin, bot]
    ports:
      - "80:80"
  
volumes:
  db_data:
  core_code:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./core
