services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7
    restart: unless-stopped

  migrations:
    build:
      context: .
      dockerfile: ./alembic/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

  admin:
    build:
      context: .
      dockerfile: ./admin/Dockerfile
    depends_on: [db, migrations]
    env_file:
      - .env
    restart: on-failure

  bot:
    build:
      context: .
      dockerfile: ./bot/Dockerfile
    depends_on: [db, migrations, redis]
    env_file:
      - .env
    restart: on-failure
    
  rq_worker:
    build:
      context: .
      dockerfile: ./billing_daemon/Dockerfile
    command: ./billing_daemon/entrypoint_worker.sh
    depends_on: [redis, db, migrations]
    env_file:
      - .env
    restart: always

  rq_scheduler:
    build:
      context: .
      dockerfile: ./billing_daemon/Dockerfile
    command: ./billing_daemon/entrypoint_scheduler.sh
    depends_on: [redis, db, migrations]
    env_file:
      - .env
    restart: always

  admin_frontend:
    build:
      context: ./admin_frontend
      dockerfile: Dockerfile
    depends_on: [admin]
    env_file:
      - ./admin_frontend/.env

  nginx:
    build: ./nginx
    depends_on: [admin_frontend]
    ports:
      - "14081:80"
  
volumes:
  db_data:
