services:
  base:
    build:
      context: .
      dockerfile: ./Dockerfile
  
  core:
    build:
      context: .
      dockerfile: ./core/Dockerfile
    depends_on: [base]
    env_file:
      - .env
    volumes:
      - core_code:/app/core

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7
    restart: unless-stopped

  migrations:
    build:
      context: .
      dockerfile: ./alembic/Dockerfile
    depends_on:
      db:
        condition: service_healthy
      base:
        condition: service_started
    env_file:
      - .env
    volumes:
      - core_code:/app/core

  admin:
    build:
      context: .
      dockerfile: ./admin/Dockerfile
    depends_on: [db, core, migrations]
    env_file:
      - .env
    restart: on-failure
    volumes:
      - core_code:/app/core

  bot:
    build:
      context: .
      dockerfile: ./bot/Dockerfile
    depends_on: [db, core, migrations]
    env_file:
      - .env
    restart: on-failure
    volumes:
      - core_code:/app/core
    
  billing_daemon:
    build:
      context: .
      dockerfile: ./scripts/Dockerfile
    depends_on: [db, core, migrations]
    env_file:
      - .env
    restart: on-failure
    volumes:
      - core_code:/app/core

  admin_frontend:
    build:
      context: ./admin_frontend
      dockerfile: Dockerfile
    depends_on: [admin]
    env_file:
      - ./admin_frontend/.env

  nginx:
    build: ./nginx
    depends_on: [admin_frontend]
    ports:
      - "14081:80"
  
volumes:
  db_data:
  core_code:
