"""first_migration

Revision ID: b73ad1f7657e
Revises: 
Create Date: 2025-06-08 21:58:17.453740

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op
from core.db.types.encrypted import EncryptedString

# revision identifiers, used by Alembic.
revision: str = 'b73ad1f7657e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server',
        sa.Column('name', sa.String(length=128), nullable=False),
        sa.Column('ip', sa.String(length=64), nullable=False),
        sa.Column('port', sa.Integer(), nullable=False),
        sa.Column('host', sa.String(length=128), nullable=False),
        sa.Column('monthly_cost', sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column('location', sa.String(length=128), nullable=False),
        sa.Column('api_key', EncryptedString(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
        sa.Column('tg_id', sa.BigInteger(), nullable=False),
        sa.Column('username', sa.String(length=64), nullable=True),
        sa.Column('created', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.Column('balance', sa.Float(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_tg_id'), 'user', ['tg_id'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    op.create_table('vpn_config',
        sa.Column('name', sa.String(length=128), nullable=False),
        sa.Column('server_id', sa.Integer(), nullable=False),
        sa.Column('owner_id', sa.Integer(), nullable=False),
        sa.Column('display_name', sa.String(length=128), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.Column('suspended', sa.Boolean(), nullable=False),
        sa.Column('suspended_at', sa.DateTime(), nullable=True),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
        sa.ForeignKeyConstraint(['server_id'], ['server.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vpn_config_name'), 'vpn_config', ['name'], unique=True)
    op.create_index(op.f('ix_vpn_config_suspended'), 'vpn_config', ['suspended'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vpn_config_suspended'), table_name='vpn_config')
    op.drop_index(op.f('ix_vpn_config_name'), table_name='vpn_config')
    op.drop_table('vpn_config')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_tg_id'), table_name='user')
    op.drop_table('user')
    op.drop_table('server')
    # ### end Alembic commands ###
