"""Add referrals to User

Revision ID: d78ffcb95ce5
Revises: 7cdd648f17a9
Create Date: 2025-06-29 18:27:13.848830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd78ffcb95ce5'
down_revision: Union[str, None] = '7cdd648f17a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('referred_by_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_user_referred_by_id'), 'user', ['referred_by_id'], unique=False)
    op.create_foreign_key(None, 'user', 'user', ['referred_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_index(op.f('ix_user_referred_by_id'), table_name='user')
    op.drop_column('user', 'referred_by_id')
    # ### end Alembic commands ###
